name: phpunit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout on commit in the repository"
      uses: actions/checkout@v2
    - name: "Build the Docker image"
      run: docker build -t yapro/api-platform-understanding:latest -f ./Dockerfile ./
    # run command in virtual machine
    - run: id
    - run: pwd
    - run: wget https://github.com/phpmd/phpmd/releases/download/2.12.0/phpmd.phar && chmod +x ./phpmd.phar
    - run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.8.0/php-cs-fixer.phar && chmod +x ./php-cs-fixer.phar
    # run commands in docker: workflows&docker understanding
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest id
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest pwd
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest ls -la
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/api-platform-understanding:latest id
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/api-platform-understanding:latest pwd
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/api-platform-understanding:latest ls -la
    # run commands in docker: CI
    - run: docker run --rm --user=root:root -v $(pwd):/app -w /app yapro/api-platform-understanding:latest chown -R www-data:www-data /app
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest ./phpmd.phar . text phpmd.xml --exclude .github/workflows,vendor,var,public/bundles --strict
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest ./php-cs-fixer.phar fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation --using-cache=no --allow-risky=yes --diff
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest composer install --optimize-autoloader --no-scripts --no-interaction
    - run: docker run --rm -v $(pwd):/app -w /app yapro/api-platform-understanding:latest bash -c "cd /app && \
      bin/console doctrine:schema:drop --full-database --force -v && \
      bin/console doctrine:schema:update --force -v && \
      bin/phpunit tests/Functional"
